# Site settings
title: Cristián A. Figueroa
email: figuercr@bc.edu
description: > # this means to ignore newlines until "baseurl:"
  PhD Student of Economics at Boston College
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cafigueroab
github_username:  cafigueroab

# Build settings
markdown: kramdown

google-site-verification: google711ac5ad99c342ea.html

paginate: 3
paginate_path: "blog/page:num"

# include: ["_publications"]

url: "https://cafigueroab.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

collections:
  work:
    output: true

defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
